<?php

namespace BOMO\BaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MeasureRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class MeasureRepository extends DocumentRepository
{
    public function multipleSearch(array $params)
    {
        $qb = $this->createQueryBuilder('m');

        $params = \BOMO\BaseBundle\Transformer\MeasureTransformer::directTransform($params);

        foreach ($params as $key => $param) {
            $qb->field($key)->equals($param);
        }

        return $qb->getQuery()->execute();
    }
}
